##  STEP1:IMPORT LIBRARIES

In [1]:
import pandas as pd
import numpy as np

## STEP2: LOAD THE DATASET

In [6]:
df = pd.read_csv("../data/Mall_Customers.csv")
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

## STEP3:DATASET OVERVIEW

In [7]:
print(df.shape)

(200, 5)

Column Informaton

In [8]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB
None

## STEP4: STATISTICAL SUMMARY

In [9]:
print(df.describe())

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

## STEP5: CHECK MISSING VALUES

In [10]:
print(df.duplicated().sum())

0

## STEP6: CHECK DUPLICATE RECORDS

In [11]:
print(df.duplicated().sum())

0

## STEP7: REMOVE DUPLICATES

In [12]:
df = df.drop_duplicates()

In [13]:
print(df.duplicated().sum())

0

## STEP8: HANDLEING MISSING VALUES

In [15]:
numeric_cols = df.select_dtypes(
    include=['int64','float64']
).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].mean())
    df.head()

Categorical Columns

In [17]:
categorical_cols = df.select_dtypes(
    include=['object']
).columns

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])
    df.head()

In [18]:
df[categorical_cols].isnull().sum()

Gender    0
dtype: int64

In [19]:
df.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

## STEP9: CHECK DATA CONSISTENCY

In [20]:
print(df[df['Age'] < 0])

Empty DataFrame
Columns: [CustomerID, Gender, Age, Annual Income (k$), Spending Score (1-100)]
Index: []

In [21]:
print(df[df['Age'] > 100])

Empty DataFrame
Columns: [CustomerID, Gender, Age, Annual Income (k$), Spending Score (1-100)]
Index: []

## STEP10 : OUTLIER DETECTION

In [22]:
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print(df[(df['Age'] < lower) |
         (df['Age'] > upper)])

Empty DataFrame
Columns: [CustomerID, Gender, Age, Annual Income (k$), Spending Score (1-100)]
Index: []

## STEP11: FEATURE ENGINEERING

In [23]:
df['Age_Group'] = pd.cut(
    df['Age'],
    bins=[0,18,35,60,100],
    labels=[
        'Teen',
        'Young Adult',
        'Adult',
        'Senior'
    ]
)

## STEP12:VERIFYING CLEANED DATA

In [24]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
 5   Age_Group               200 non-null    category
dtypes: category(1), int64(4), object(1)
memory usage: 8.3+ KB
None
CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
Age_Group                 0
dtype: int64